### PR TITLE
add parent code in element code

### PR DESCRIPTION
**Pull request by doydoy44**

### CODE REVIEW

**Comment by doydoy44** [comment]
@fstueber  : I hope I've understood how the code column works :)

**Comment by fstueber** [comment]
Hi, you've understood the pattern quite well. But I have made another update in the meantime. Please have a look at it. The main idea now is to keep zones/academies and regions/divisions apart.

As an example: 
``` pws
curl -X 'GET' 'https://openholidaysapi.org/SchoolHolidays?countryIsoCode=FR&languageIsoCode=FR&validFrom=2024-01-01&validTo=2024-01-02' -H 'accept: text/plain'
```
gives you:
``` json
[
  {
    "id": "a84882bb-7f11-42a6-a4c1-a6eeafa2c621",
    "startDate": "2023-12-24",
    "endDate": "2024-01-07",
    "type": "School",
    "name": [
      {
        "language": "FR",
        "text": "Vacances de Noël"
      }
    ],
    "nationwide": false,
    "subdivisions": [
      {
        "code": "FR-IF",
        "shortName": "IF"
      },
      {
        "code": "FR-CV",
        "shortName": "CV"
      },
      {
        "code": "FR-AR",
        "shortName": "AR"
      },
      {
        "code": "FR-PL",
        "shortName": "PL"
      },
      {
        "code": "FR-NA",
        "shortName": "NA"
      },
      {
        "code": "FR-BF",
        "shortName": "BF"
      },
      {
        "code": "FR-GE",
        "shortName": "GE"
      },
      {
        "code": "FR-BT",
        "shortName": "BT"
      },
      {
        "code": "FR-SP",
        "shortName": "SP"
      },
      {
        "code": "FR-ZC",
        "shortName": "ZC"
      },
      {
        "code": "FR-ZB",
        "shortName": "ZB"
      },
      {
        "code": "FR-HF",
        "shortName": "HF"
      },
      {
        "code": "FR-ZA",
        "shortName": "ZA"
      },
      {
        "code": "FR-OC",
        "shortName": "OC"
      },
      {
        "code": "FR-PC",
        "shortName": "PC"
      },
      {
        "code": "FR-NO",
        "shortName": "NO"
      },
      {
        "code": "FR-CO",
        "shortName": "CO"
      }
    ]
  }
]
```
What do you think?

**Comment by fstueber** [comment]
Yes right

**Comment by doydoy44** [comment]
Super,
I'll close the PR or do you want anything else?

**Comment by fstueber** [comment]
No, everything is fine. Thank you for your work.

**Pull request closed without merging**
