### PR TITLE
add: Portuguese subdivisions and public holidays (national and district level)

### PR DESCRIPTION
**Pull request by 48design**
This PR adds some initial data for Portugal:
* subdivisions: The 18 districts and 2 autonomous regions, as well as their 308 municipalities
* Public holidays on national and district level from 2020 to 2030
* Add entries to countries and languages

Unfortunately, the regional/municipal holidays seem to be quite scattered and I couldn't yet locate a single resource covering all of them. We'll also need an official resource for school holidays. But at least it's a start.

### CODE REVIEW

**Comment by fstueber** [comment]
Great!!! Will have a look later on the data.

My findings on Portuguese holiday sources:

School holidays:

+ 2019/2020 - [Despacho n.º 5754-A/2019](https://diariodarepublica.pt/dr/detalhe/despacho/5754-a-2019-122609690)
+ 2020/2021 - [Despacho n.º 1689-A/2021](https://diariodarepublica.pt/dr/detalhe/despacho/1689-a-2021-157360559)
+ 2021/2022 - [Despacho n.º 12123-M/2021](https://diariodarepublica.pt/dr/detalhe/despacho/12123-m-2021-175816929)
+ 2022/2023 and 2023/2024 - [Despacho n.º 8356/2022](https://diariodarepublica.pt/dr/detalhe/despacho/8356-2022-185829850)

Public holidays:

+ [Lei n.º 7/2009, Código do Trabalho - CT - Subsecção IX](https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2009-34546475-46746675)
+ [Lei n.º 8/2016, de 1 de abril](https://diariodarepublica.pt/dr/detalhe/lei/8-2016-74007209)
+ [Decreto Regional n.º 27/79/M, de 9 de novembro](https://diariodarepublica.pt/dr/detalhe/decreto-regional/27-1979-363277)
+ [Decreto Legislativo Regional n.º 18/2002/M, de 8 de novembro](https://diariodarepublica.pt/dr/detalhe/decreto-legislativo-regional/18-425483)

**Comment by fstueber** [comment]
I have created an [issue](https://github.com/openpotato/openholidaysapi.data/issues/26) for further discussion.

**Comment by igordevezas** [comment]
Hello guys, I dont know what else to report this, but the information for the next Páscoa (Easter) for 2025 is totally wrong. It is showing:
```
{
    "id": "6dc9e537-28fc-43f1-b739-1c831c6e2f34",
    "startDate": "2025-04-07",
    "endDate": "2025-04-07",
    "type": "Public",
    "name": [
      {
        "language": "PT",
        "text": "Sexta-feira Santa"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  }
```

  ```
{
    "id": "035df30c-4f45-4e47-9205-75e2b5dcf802",
    "startDate": "2025-04-09",
    "endDate": "2025-04-09",
    "type": "Public",
    "name": [
      {
        "language": "PT",
        "text": "Domingo de Páscoa"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  }
```

the real dates are:

Presentify 2024-11-12 18 03 34

Can I support you on something?

**Comment by fstueber** [comment]
Fixed. See #70

**Pull request merged**
