### PR TITLE
add subdivisions for specifics french holidays #48

### PR DESCRIPTION
**Pull request by doydoy44**

### CODE REVIEW

**Review by pYassine — APPROVED** [review]

**Comment by doydoy44** [comment]
French school dates :

- https://www.service-public.fr/particuliers/vosdroits/F31952
- https://www.service-public.fr/simulateur/calcul/Dates_Vacances_Scolaires

Departments and regions division :

- https://fr.wikipedia.org/wiki/Acad%C3%A9mie_(%C3%A9ducation_en_France)
- https://fr.wikipedia.org/wiki/D%C3%A9partement_fran%C3%A7ais
- https://fr.wikipedia.org/wiki/R%C3%A9gion_fran%C3%A7aise

French isoCode :

- https://fr.wikipedia.org/wiki/ISO_3166-2:FR

**Comment by fstueber** [comment]
Hi, thanks a lot for the work. Will have a look on everything in the next week.

**Comment by fstueber** [comment]
Hi there, we have a conflict from the previous pull request #54. Would be great if you can resolve this. And one more: The German translation for french department is **Department** ("Abteilung" is a literal translation, but does not fit here). Thanks!!!

**Comment by fstueber** [comment]
Again thanks a lot for the contribution. I have merged and updated some details:

- Subdivisions: I have taken the original English and French translations for subdivision categories from the ISO platform. See: https://www.iso.org/obp/ui/#iso:code:3166:FR. 
- German translation: I did some minor changes there.

**Comment by fstueber** [comment]
There is still one problem that should be solved in one way or another:

Part of the French subdivision are the holiday zones A, B and C. The school districts (académie) are located under these zones. This is only interesting for school holidays. At the same time, there are regions that have A, B or C as their parent. The codes (not iso codes) should be FR-ZA-AR,  FR-ZA-BF etc. instead of FR-AR, FR-BF, otherwise an API call for FR-AR would not give any result. Same for departments: FR-01 must be FR-ZA-AR-01

Possible solutions:
+ Encode the zone into the code of the regions and departments e.g. FR-AR > FR-TA-AR and FR-01 > FR-ZA-AR-01
+ Remove the parent from regions so we get FR-AR and FR-01 > FR-AR-01

What do you think?

**Comment by fstueber** [comment]
One more option: Do not use Zones A, B, C (and school districts) at all. Instead us directly the regions. This works, if all regions cover all zones. With this we have no conflicts.

**Comment by doydoy44** [comment]
Sorry, I didn't understand the logic behind the codes.

The French case is quite complicated.
Officially, school holidays are defined by academic zones.
But people live in cities that are in departments that are in regions that are in France.
I haven't found any official documents making the link between department and academy, but there's this wikipedia page that lists departments by zone: https://fr.wikipedia.org/wiki/Acad%C3%A9mie_(%C3%A9ducation_en_France)

In practice, the administrative regions correspond to the academic regions.

If that's OK with you, since school holidays are defined by academic zone, I'd keep the principle that an academic zone contains regions that contain departments.
If that's OK with you, I'll make a new PR for that.

**Pull request merged**
